name: Build and Deploy Flask App

on:
    push:
        branches:
            - master

jobs:
    build:  
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
            uses: actions/checkout@v2
            
            - name: Log in to Docker Hub (or other registry)
            run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Build Docker image
            run: docker build -t yourusername/flask-app:latest .

            - name: Push Docker image
            run: docker push yourusername/flask-app:latest
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Get application URL
            run: echo "Your application is accessible at:$APPLICATION_URL"
            env: 
                APPLICATION_URL: ${{ steps.get_application_url.outputs.url }}
        

